MatchMakingSim/urls.py
from django.conf.urls import url
from . import views

app_name = 'matches'
urlpatterns = [
    url(r'^$', views.intro, name='intro'),
    url(r'^matching/$', views.match_engine, name='ajax-engine')
]

blog/urls.py
from django.conf.urls import url
from . import views
# from django.views.generic import DetailView, ListView
# from blog.models import Post

app_name = "blogs"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="List"),
    url(r'^(?P<pk>\d+)$', views.DetailView.as_view(), name="Detail")
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^webgame/',include('webgame.urls')),
    url(r'^MMS/',include('MatchMakingSim.urls')),
    url(r'^blog/',include('blog.urls')),
    url(r'^', include('personal.urls'))
]

personal/urls.py
from django.conf.urls import url
from . import views
app_name = "home"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^email/$', views.contactForm, name='contact')
]

webgame/urls.py
from django.conf.urls import url
from . import views

app_name='games'
urlpatterns=[
    url(r'^$',views.index, name='welcome'),
    url(r'^gameon/$',views.game_engine, name='engine')
]

MatchMakingSim/models.py
from django.db import models

# Create your models here.

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Post(models.Model):
    
    title=models.CharField(max_length=140)
    body=models.TextField()
    date=models.DateTimeField()
    
    def __str__(self):
        return self.title
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

webgame/models.py
from django.db import models

# Create your models here.

MatchMakingSim/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .MMS.Match import Match, readPlayerFile
# from django.http import HttpResponseRedirect, HttpResponse
import os
script_dir = os.path.dirname(__file__)  # abs dir the script in
player_path = os.path.join(script_dir, "MMS/players.txt")
male_path = os.path.join(script_dir, "MMS/male.txt")
female_path = os.path.join(script_dir, "MMS/female.txt")


# Create your views here.
def intro(request):
    return render(request, 'MMS/main-page.html')


def match_engine(request):
    ret = {
        "Error": False,
        "ErrMsg": '',
        "result": []
    }

    if request.method == 'POST':
        if not request.POST:
            ret['Error'] = True
            ret['ErrMsg'] = "Empty Input."
            return JsonResponse(ret)
        gen = 1 if request.POST['gender'] == "Man" else 0

        appearence = request.POST['appearence']
        personality = request.POST['personality']
        wealth = request.POST['wealth']
        exAppear = request.POST['exAppear']
        exPerson = request.POST['exPerson']
        exWealth = request.POST['exWealth']

        if(int(exAppear)+int(exPerson)+int(exWealth) == 100):
            playerTuple = (gen, int(appearence), int(personality), int(wealth),
                           int(exAppear), int(exPerson), int(exWealth))
            match = Match(male_path, female_path)
            match.kick_start(playerTuple)
            if(len(match.resultLog) == 0):
                ret["Error"] = True
                ret["ErrMsg"] = "Empty log"
                return JsonResponse(ret)
            ret["result"] = match.resultLog
            return JsonResponse(ret)
        else:
            ret["Error"] = True
            ret["ErrMsg"] = "Invalid Input."
            return JsonResponse(ret)
    # get method for validation
    playerList = readPlayerFile(player_path)
    match = Match(male_path, female_path)
    for p in playerList:
        match.kick_start(p, 0)
    # check the result
    if "28" in match.resultLog[0]:
        ret["ErrMsg"] += "1"
    else:
        ret["ErrMsg"] += "0"
    if "33" in match.resultLog[-4]:
        ret["ErrMsg"] += "1"
    else:
        ret["ErrMsg"] += "0"
    ret["Error"] = False if ret["ErrMsg"] == "11" else True
    ret["result"] = match.resultLog
    return JsonResponse(ret)

blog/views.py
from django.shortcuts import render


from django.views import generic
from .models import Post
# Create your views here.
class IndexView(generic.ListView):
    template_name = "blog/blog.html"
    context_object_name = 'latest_posts_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Post.objects.all().order_by("-date")[:25]
        
class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

personal/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core.mail import send_mail, BadHeaderError


# Create your views here.
def index(request):
    return render(request, 'personal/home.html')


def contactForm(request):
    ret = {
        "err": False,
        "msg": ""
    }
    if request.method == "POST":
        name = request.POST['senderName']
        address = request.POST['EmailAddr']
        phone = request.POST['telephone']
        message = request.POST['Msg']

        if not name or not address or not message:
            ret["err"] = True
            ret["msg"] = "Fill out the required field."
            return JsonResponse(ret)
        elif "@" not in address:
            ret["err"] = True
            ret["msg"] = "Invalid Email Address."
            return JsonResponse(ret)
        else:
            try:
                send_mail(name+" leaves a message", message+phone, address,
                          ['zg900311@outlook.com'])
                ret["msg"] = "Email Sent."
                return JsonResponse(ret)
            except BadHeaderError:
                ret["err"] = True
                ret["msg"] = "Bad header error."
                return JsonResponse(ret)

webgame/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# , HttpResponse

# from django.urls import reverse
from django.core.urlresolvers import reverse
from .game import map


# Create your views here.
def index(request):
    request.session['name'] = map.start.name
    request.session['description'] = map.start.description
    request.session['count'] = 9
    return HttpResponseRedirect(reverse('games:engine'))


def game_engine(request):
    room = map.look_up.get(request.session['name'], None)
    if request.method == 'POST':
        if room.name == 'keypad':
            room.count = request.session['count']
            request.session['count'] -= 1

        action = request.POST['your_move']
        if action:
            if room.check_path(action):
                room = room.go(action)
            else:
                room = room.go('*')
        if room:
            request.session['name'] = room.name
            request.session['description'] = room.description
            return HttpResponseRedirect(reverse('games:engine'))
        else:
            request.session.flush()
            return render(request, 'webgame/you_died.html')
    else:
        context = {
            'name': room.name,
            'description': room.description
        }
        if room.name in ['death', 'You Won', 'You Lost']:
            context['end'] = True
            request.session.flush()
        if room.name == 'keypad':
            context['tries_left'] = request.session['count']

        return render(request, 'webgame/show_room.html', context)

MatchMakingSim/templates/MMS/includes/modal-form.html
 {%block content%}
 {% load staticfiles%}

<button type="button" class="btn btn-primary btn-lg " data-toggle="modal" data-target="#exampleModal"> Launch the Demo</button>
<button type="button" class="btn btn-primary btn-lg" data-loading-text="tesing" data-complete-text="test completed" id="valid">Validation</button>
<button type="button" class="btn btn-primary btn-lg " id="reset-page">RESET</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Tell me about you</h4>
      </div>
      <div class="modal-body">
	      <form class="form-horizontal" id="info-form" method="post" action="{% url 'matches:ajax-engine'%}">
	{% csrf_token %}
          <p class="text-center" id="form-status"></p>
          <div class="row">
            <div class="col-md-5">
              <div class="form-group" id="appearenceBox">
                <label for="inputAppearence" class="col-sm-4 control-label">Appearence</label>
                <div class="col-sm-8">
                  <input type="number" name="appearence" class="form-control" id="inputAppearence" placeholder="0~100" required>
                </div>
              </div>
              <div class="form-group" id="personalityBox">
                <label for="inputPersonality" class="col-sm-4 control-label">Personality</label>
                <div class="col-sm-8">
                  <input type="number" name="personality" class="form-control" id="inputPersonality" placeholder="0~100"required>
                </div>
              </div>
              <div class="form-group" id="wealthBox">
                <label for="inputWealth" class="col-sm-4 control-label">Wealth</label>
                <div class="col-sm-8">
                  <input type="number" name="wealth" class="form-control" id="inputWealth" placeholder="0~100"required>
                </div>
              </div>
             <small class="text-danger" id="err1"></small>
            </div>
            <div class="col-md-7">
              <div class="form-group" id="exAppearenceBox">
                <label for="inputExAppear" class="col-sm-6 control-label">Expect Appearence</label>
                <div class="col-sm-6">
                  <input type="number" name="ex-appearence" class="form-control" id="inputExAppear" placeholder="0~100" required>
                </div>
              </div>
              <div class="form-group" id="exPersonalityBox">
                <label for="inputExPerson" class="col-sm-6 control-label">Expect Personality</label>
                <div class="col-sm-6">
                  <input type="number" name="ex-personality" class="form-control" id="inputExPerson" placeholder="0~100" required>
                </div>
              </div>
              <div class="form-group" id="exWealthBox">
                <label for="inputExWealth" class="col-sm-6 control-label">Expect Wealth</label>
                <div class="col-sm-6">
                  <input type="number" name="ex-wealth" class="form-control" id="inputExWealth" placeholder="0~100" required>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <span id="gender-text">Now tell me you are a : </span>
            <label class="radio-inline">
              <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="Man"> Man
            </label>
            <label class="radio-inline">
              <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="Woman"> Woman
            </label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="LaunchSim" data-complete-text="Matching Complete" data-loading-text="Matching">Tell Him</button>
      </div>
    </div>
  </div>
</div>

 {%endblock%}

MatchMakingSim/templates/MMS/includes/result.html
 {%block content%}
 {% load staticfiles%}
    <div class="panel panel-default" id="result-panel">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour" id="ret-msg">
          Here is your result:
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="list-group" id="logBox">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Morbi leo risus</li>
      <li class="list-group-item">Porta ac consectetur ac</li>
      <li class="list-group-item">Vestibulum at eros</li> 
      </div>
    </div>
  </div>


{%endblock%}

MatchMakingSim/templates/MMS/main-page.html
{%extends "personal/header.html"%}
{%block content%}
 {% load staticfiles%}
<!--style sheet-->
<link rel="stylesheet" href="{% static 'MMS/css/style.css'%}" charset="utf-8" type="text/css" />
<!--javascript-->
<!--<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>-->


<div class="jumbotron intro-box">
<h1>A Match Making Simulation</h1>
<h3 class="text-warning">In order to carry out this simulation, here are some instructions you need to know:</h3>
    <ul class="rules-style">
      <li class="text-info">First tell me <span class="text-warning">3 marks, in the scale of 100,</span>  on your appearence, personality and wealth.</li>
      <li class="text-info"> Then tell me how you value those three qualities of your match, specifically, give me 3 ratios about your expectation for appearence, personality and wealth of your match and <span class="text-warning"> those 3 percentage should add up to 100.</span> </li>
      <li class="text-info"> Lastlly, <span class="text-warning">tell me your gender</span>, natraully.</li>
      <li class="text-info"> <span class="text-warning">Launch the Demo</span> is a normal round of matching process for you with the information you provide.</li>
      <li class="text-info"><span class="text-warning">Validation</span> is a functional test for this simulation, which process 100 players in the script to see if they could found their supposed match, thus, to see if the algorithm is working properly and efficiently.</li>
      <li class="text-info"> <span class="text-warning"> RESET</span> button is for reset the page after the operations mentioned above, which makes it ready to handle another request.</li>
        
    </ul>
    {%include "MMS/includes/collapse.html"%}
    {%include "MMS/includes/modal-form.html"%}
</div>
    {%include "MMS/includes/result.html"%}
	<script type="text/javascript" src="{% static 'MMS/js/ajax-modal.js' %}"></script>
{%endblock%}

blog/templates/blog/blog.html
{% extends "personal/header.html"%}


 {% block content %}
    <div class="row">
	
        <div class="col-md-2">
           <div>
            <!-- <ul class=" nav nav-tabs nav-stacked">
              <li role="presentation" ><a href="#intro" >About me</a></li>
              <li role="presentation" ><a href="#projects">Projects I've Done</a></li>
              <li role="presentation" ><a href="#contact-info">Contact me</a></li>

            </ul> -->
            </div>
        
        </div>
        <div class="col-lg-8">
            <div class="container-fluid">
                <!--<table>-->
                    {% for post in object_list %}
                    <div class="well">
                        <h5><a href="{% url 'blogs:Detail' post.id %}"
                                >{{post.title}} </a></h5>
                        <p>{{post.body|truncatewords:5|safe|linebreaks}}</p>
                        <ul class="list-inline list-unstyled">
                        <li>
                        <a href="{% url 'blogs:Detail' post.id %}"
                            >More...</a>
                        </li>
                        <li>|</li>
                            <li><span><i class="glyphicon
                            glyphicon-calendar"></i>{{ post.date|date:"Y-m-d" }}
                                </span></li>
                            <li>|</li>
                            <span><i class="glyphicon glyphicon-comment"></i>
                                no comment(not yet implemented)</span>
                        </ul>
                         
                    </div>
                    {% endfor %}
                <!--</table>-->
                
            </div>
        </div>
        <div class="col-md-2">
            <div class="list-group">
              <a href="#" class="list-group-item disabled">Timeline</a>
              <a href="#" class="list-group-item disabled">Most Recent</a>
              <a href="#" class="list-group-item disabled">My Story</a>
                <a href="#" class="list-group-item disabled">About Projects</a>
              <a href="#" class="list-group-item disabled"> Study Notes</a>
                <a href="#" class="list-group-item disabled">Other Things</a>
            </div>
           <!-- <div>
            <ul class=" nav nav-tabs nav-stacked">
              <li><a href="#intro" >About me</a></li>
              <li ><a href="#projects">Projects I've Done</a></li>
              <li><a href="#contact-info">Contact me</a></li>

            </ul>
            </div> -->
        </div> 
    </div>
{%endblock%}

blog/templates/blog/post.html
{% extends "personal/header.html"%}

{% block content %}
<a id="top-page"></a>
<div class="container">
    <div class="row">
        <div class="col-md-2">
        </div>

        <div class="col-md-8 col-sm-12">
            <div class="container-fluid">
               <h3>{{post.title}}</h3>
                <h6 class="text-center">on {{post.date}}</h6>
                <div >
                    {{post.body|safe|linebreaks}}
                </div>
            </div>
        </div>
         <div class="col-md-2">
             <div id="sidebar">
            <ul class=" list-group">
              <li role="presentation" class="list-group-item disabled"><a
                      href="#"> Related Posts</a></li>
              <li role="presentation" class="list-group-item disabled"><a
                      href="#">Comment Section</a></li>
              <li role="presentation" class="list-group-item"><a
                      href="#top-page">Back to Top</a></li>
            </ul>
            </div>
     </div>
    </div>
</div>

{%endblock%}

personal/templates/personal/includes/banner.html
{%block content%}
  {% load staticfiles%}
<!--style sheet-->
<link rel="stylesheet" href="{% static 'personal/css/top-banner-style.css'%}" charset="utf-8" type="text/css" />
<!--javascript-->
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
<script type="text/javascript" src="{% static 'personal/js/index.js' %}"></script>

<nav id="header" class="navbar navbar-fixed-top">
            <div id="header-container" class="container navbar-container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed text-center" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="brand" class="navbar-brand" href="{% url 'home:index' %}"><strong>Welcome to Gong Zhang's Website</strong></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav nav-pills navbar-right ">
                        <li ><a href="{% url 'home:index' %}">Home</a></li>
                        <li ><a href="{% url 'blogs:List' %}">Blog</a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                              Projects <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'games:welcome' %}">Webgame</a></li>
                              <li role="separator" class="divider"></li>
			      <li><a href="{%url 'matches:intro' %}">Match Making Simulation</a></li>
                          </ul>
                        </li>
                    </ul>
                </div><!-- /.nav-collapse -->
            </div><!-- /.container -->
        </nav><!-- /.navbar -->
{%endblock%}

personal/templates/personal/includes/contact-form.html
 {%block content%}
{% load staticfiles%}
<link rel="stylesheet" href="{% static 'personal/css/contact-form-style.css'%}"charset="utf-8" type="text/css" />

<section id="contact">
    <div class="section-content">
        <h3 class="section-header">Get in <span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s"> Touch with me</span></h3>
        <!-- <h4>Leave anything you want, and I'll get back to you as soon as I can.</h4> -->
        <h4 class="text-warning">This section currently not working, just
            contact me by Email on the
            left section, I'll fix it soon</h4>
      </div>
  <div class="contact-section">
      <div class="container-fluid">
	  <form id="contact-form" method="post" action="{% url 'home:contact' %}">
		<div class="row">
            <div class="col-md-6 form-line">
              <div class="form-group">
                <label for="exampleInputUsername">Your name</label>
                <input type="text" class="form-control" id="sender-name" placeholder=" Enter Name" required>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail">Email Address</label>
                <input type="email" class="form-control" id="InputEmail" placeholder=" Enter Email address" required>
              </div>	
              <div class="form-group">
                <label for="telephone">Mobile No.</label>
                <input type="tel" class="form-control" id="telephone" placeholder=" Enter 10-digit mobile no.">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for ="description"> Message</label>
                <textarea  class="form-control" id="description" placeholder="Enter Your Message"></textarea>
              </div>
              <div>
                <button type="submit" id="contact-send" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i>  Send Message</button><br>
                <small class="text-danger" id="status-line"></small>
              </div>
          </div>
		</div>
    </form>
  </div>
 </div>
</section>

 {%endblock%}

personal/templates/personal/includes/project1.html
 {%block content%}
 {% load staticfiles%}
<div class="thumbnail">
            <img class="img-responsive" src="http://prodimage.images-bn.com/pimages/9780321884916_p0_v2_s1200x630.jpg" alt="web game">
            <div class="caption">
              <h3>A small text-based Webgame</h3>
              <p>This is the final exercise of the book above that I read to
              learn python, it's implemented on web.py framework in the book,
              but I move it to Django, as a start point to get to know this
              framework. I learnt: <ul>
                <li>Basic python OOP analysis and design, implementing unit
                    test cases both local and in the Django framework.</li>
                <li>Knowledge about how website works: requests, get, post
                    method.</li>
                <li>Features of Django framework like test, session, Jinja
                    logic, post form handling.</li>
                <!-- <li>How session works, which is basically the core of this
                    project.</li> -->
            </ul></p>
            <p> Please note that this game is still very
            primitive, just for the purpose of getting the basic ideas of web
            development.<br>But, I'm planning on enhancing the styles of this page and
            most importantly, adding features like batter language processing in
            the furture. </p>
              <p>
                  <a href="{% url 'games:welcome' %}" class="btn btn-primary" role="button">Learn more</a>   
                  <a
                      href="https://github.com/Gontreal/hello-django/tree/master/webgame" class="btn btn-default" role="button">Source Code</a>
             </p>
            </div>
          </div>
 {%endblock%}
 

personal/templates/personal/includes/project2.html
 {%block content%}
 {% load staticfiles%}
<div class="thumbnail">
            <img class="img-responsive" src="http://cdn.quotesgram.com/img/51/80/1102522291-online-dating2-1h3togt.jpg" alt="image of projcect 2">
            <div class="caption">
              <h3>A match making simulation</h3>
              <p>This project is the major reason why I made this website. It
              was originally a c++ project that a friend of mine introduced to
              me. Back then, I just finished studying c++ from C++ Premier and
              half way through the study of algorithms and data structures, and
              this was the start project for me to get my hand dirty.
              It involves implementing an efficient sorting algorithm for the
              matching process(I uesed priority queue), and a soid structure
              of classes working together to encapsulate the algorithm and
              to handle this matching process. Detail specs and explainations are in
              the project page and my blog.</p>
              <p> The main featrue of this project is as follows:
              <ul>
                  <li>High perfromance c++ code with well designed algorithmic
                      and data structure implementation.</li>
                  <li>Hybrid programming(python and c++) powered by boost library to
                  make the original program interact with Django yet ensure
                  its level of performace.</li>
                  <li>Implemented AJAX protocol with jQuery to enhance the
                      response time of the program and delegate some tasks to
                      client side. </li>
              </ul>
              </p>
              <p> Click learn more button to visit the
              project page and source code button to view the independent
              project of this web application. </p>
              <p>
                  <a href="{%url 'matches:intro'%}" class="btn btn-primary" role="button">Learn more</a> 
                  <a href="https://github.com/Gontreal/Match-Making-Simulation" class="btn btn-default" role="button">Source Code</a>
              </p>
            </div>
          </div>
 {%endblock%}

personal/templates/personal/includes/project3.html
 {%block content%}
 {% load staticfiles%}
<div class="thumbnail">
            <img class="img-responsive" src="http://www.dianaglavnik.com/uploads/sites/2578/public/keep-calm-and-visit-my-blog-20.png" alt="my blog pic">
            <div class="caption">
              <h3>My Personal Blog</h3>
              <p>This is the first project I did along with the website
              itself. I followed a course about making a website on Django
              framework. And this blog application was the example. So, this
              project helped me learnt:
            <ul>
                <li>Django project structure, like views, urls, and setting,
                    admin modules to manage the website.</li>
                <li>Django model class and how it's an abstraction of data
                    base interface int order to mangage data inplace rather
                    than write another piece of data base code to manage data.</li>
            </ul>  </p>
            <p>Please also note that this blog app, like the webgame app, mainly
            serves as an exercise for me to get the idea of web development
            rather than an actual functioning app, but I have plans to improve
            it to a well-designed blog module like so many other examples
            online. The first step is to impletment a index panel that could
            sort or retrieve entries based on date or most recent updates. And
            also a coment section.  </p>
              <p>
                  <a href="{%url 'blogs:List'%}" class="btn btn-primary" role="button">Learn more</a> 
                  <a
                      href="https://github.com/Gontreal/hello-django/tree/master/blog" class="btn btn-default" role="button">Source Code</a>
                </p>
            </div>
          </div>
 {%endblock%}

personal/templates/personal/includes/social-icon.html
 {%block content%}
 {% load staticfiles%}
<link rel="stylesheet" href="{% static 'personal/css/social-icon-style.css'%}" charset="utf-8" type="text/css" />
 <div class="sicon">
  <div class="col-md-1 col-sm-3 col-xs-6 text-center">
    <div class="icon-circle">
      <a href="https://www.facebook.com/profile.php?id=100006437729513" class="ifacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
    </div>
  </div>

  <!-- <div class="col-md-1 col-sm-3 col-xs-6 text-center">
    <div class="icon-circle">
      <a href="https://twitter.com/IMP_ZG" class="itwittter" title="Twitter"><i class="fa fa-twitter"></i></a>
    </div>
  </div> -->

  <div class="col-md-1 col-sm-3 col-xs-6 text-center">
    <div class="icon-circle">
      <a href="https://github.com/Gontreal" class="igithub" title="Github"><i class="fa fa-github"></i></a>
    </div>
  </div>

  <div class="col-md-1 col-sm-3 col-xs-6 text-center">
    <div class="icon-circle">
      <a href="https://www.linkedin.com/in/gong-zhang/" class="iLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
    </div>
   </div>

</div>
 {%endblock%}

webgame/templates/webgame/show_room.html
{% extends "personal/header.html"%}

{% block content %}
<div class="container">
    <h1>{{name}}</h1>
    <pre>{{description}}</pre>

    {% if end %}
            <a href="{% url 'games:welcome' %}"> Play Again?</a>

    {%else%}
        <form action="{% url 'games:engine'%}"  method="POST" class="form-inline">
            {% csrf_token %}
             <input type="text" name="your_move" class="form-control" placeholder="What's your next move?">
            <button type="submit" class="btn btn-primary">Confirm</button>
            <br>
            {% if tries_left %}
                <small class="text-danger"> {{tries_left}} times left.</small>
            {% endif %}
        </form>
   {% endif %}
</div>

 
{%endblock%}

webgame/templates/webgame/you_died.html
{% extends "personal/header.html"%}

{% block content %}
    <div class="container">
        <h1>You Died!</h1>

        <p>Looks like you bit the dust.</p>

        <p><a href="{% url 'games:welcome' %}"> Play Again</a></p>
    </div>

    
{%endblock%}